### ISSUE TITLE
Boot loop after install

### ISSUE THREAD

**Issue by tolkonepiu** [radxa-build/rockpi-4b#1]
I tried to upgrade from Ubuntu 20 Server (Linux 4.4) to Debian Bullseye (CLI) from the latest release. I installed it on an NVMe, and the previous system was also installed there (I flashed uboot). As a result, the system doesn't boot at all. Is there any guide for installing new builds of the system on a Rock Pi 4B?

**Comment by RadxaYuntian** [comment]
You can't really "upgrade" Ubuntu to Debian. We have also changed the build system between Debian 10 and Debian 11, so they are incompatible as well.

**Comment by tolkonepiu** [comment]
@RadxaYuntian sorry, i dont want upgrade system, i want install a new one.

**Comment by tolkonepiu** [comment]
Install completely from scratch, the only thing that will remain is the uboot version, although I’m not sure that it doesn’t need to be changed either.

**Comment by RadxaYuntian** [comment]
You might have some bootloader left in SPI. Though if you are not having boot issue you don't have to fix it.

**Comment by tolkonepiu** [comment]
I am indeed having a problem launching Debian from an NVMe, which I downloaded from the releases of this repository. But there were no issues launching Ubuntu Server 20, which also ran from NVMe. However, Ubuntu Server 20 with kernel 4.4 is already outdated, and I want to switch to a new Linux kernel. From your guides, I understood that it is better to use Debian instead of Ubuntu.

I downloaded it from the releases, wrote it to the NVMe using Etcher. But as a result, it does not launch.

Now I have again returned to Ubuntu 20 without any problems, so I can't fully understand where the problem lies.

**Comment by tolkonepiu** [comment]
Ubuntu Jemmy, downloaded from this repository, also does not start from NVMe on Rock Pi 4B.

**Comment by RadxaYuntian** [comment]
Please provide serial boot log when using our latest Debian image.

**Comment by tolkonepiu** [comment]
I fix the problem with armbian u-boot firmware. Thank you!
